version: "3.4"
networks:
    bustardnest:
services:
  portainer:
        image: portainer/portainer:latest
        container_name: portainer
        restart: unless-stopped
        logging:
            driver: 'json-file'
            options:
                max-file: '5'
                max-size: '10m'
        expose:
            - 9000
        environment:
            - TZ=${TZ}
            - PUID=${PUID}
            - PGID=${PGID}
        volumes:
            - './portainer:/data'
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/etc/localtime:/etc/localtime:ro'

  watchtower:
      image: v2tec/watchtower
      container_name: watchtower
      restart: unless-stopped
      logging:
          driver: 'json-file'
          options:
              max-file: '5'
              max-size: '10m'
      environment:
          - TZ=${TZ}
          - PUID=${PUID}
          - PGID=${PGID}
          - WATCHTOWER_NOTIFICATIONS=email
          - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${SMTP_FROM}
          - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL}
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_SERVER}
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT}
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USER}
          - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASS}
      volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
          - '/etc/ssl/certs:/etc/ssl/certs'
      command: --schedule @midnight --cleanup

  netdata:
      image: titpetric/netdata
      container_name: netdata
      restart: unless-stopped
      logging:
          driver: 'json-file'
          options:
              max-file: '5'
              max-size: '10m'
      expose:
          - 19999
      environment:
          - TZ=${TZ}
          - PUID=${PUID}
          - PGID=${PGID}
      cap_add:
          - SYS_PTRACE
      volumes:
          - '/proc:/host/proc:ro'
          - '/sys:/host/sys:ro'
          - '/etc/localtime:/etc/localtime:ro'
          - '/var/run/docker.sock:/var/run/docker.sock'