version: "3.5"
networks:
    - bustardnest
services:
    swag:
        image: ghcr.io/linuxserver/swag
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ} 
            - URL=${URL}
            - SUBDOMAINS=wildcard
            - VALIDATION=dns
            - CERTPROVIDER=zerossl
            - DNSPLUGIN= route53
            - EMAIL=${EMAIL}
        volumes:
            - ./swag:/config
        ports:
            - 443:443
        restart: unless-stopped

    bind9:
        restart: always
        image: labbsr0x/dns-bind9
        ports:
            - "53:53/udp"
            - "53:53/tcp"
        volumes:
            - ./bind9:/data        
